Config = {}


Config.vorp = true
Config.redem = false
Config.metadata = true 
Config.onesync = true 
Config.bucketblock = 500
Config.useDecayitems = true

--New Item Blacklist for storage items in this list will not beable to be stored in the storage
Config.ItemBlacklistfromhorse = {
	"wood",
	"stone",
	"metal",
	"p_ambpack02x",
	--add other items

}
Config.ItemBlacklistfromwagon = {
	"wood",
	"stone",
	"metal",
	"p_ambpack02x",
	--add other items

}
Config.disablehorsecallinjail = true -- disables horse/wagon calling in siska jail
Config.allowpolicecall = true -- allows police to call horses in siska 
Config.policejobs = {"police","marshal","doctor"} -- jobs that can call horses in siska jail

Config.autoclose = true

Config.adminwebhook = ""
Config.webhookavatar = "https://www.pngall.com/wp-content/uploads/2016/03/Horse-PNG-8.png"
Config.exploitwebhook = ""

----------------------------------
-- THIS IS ONLY FOR REDEM USERS -- 
Config.HorseLocker = true -- If this is true, horses inventories will be enabled
Config.WagonLocker = true -- If this is true, wagon inventories will be enabled
----------------------------------
Config.searchhorses = true 
Config.searchwagons = true 
Config.policeonly = false
Config.searchjobs = {"police"}

--------------------------------------
Config.lockedtojob = true -- if set to true, wagons listed below will not be called if the player no longer has the locked job 

Config.lockedwagons = { -- wagons that are locked to a job and cant be called if the player doesnt have the job

	["gatchuck_2"] = {"police"}, 
	["policeWagongatling01x"] = {"police"}, 
	["ArmySupplyWagon"] = {"police"}, 
	["wagonarmoured01x"] = {"police"}, 
	["wagonPrison01x"] = {"police"}, 
}
--------------------------------------
Config.callnearstable = false -- turn to true to allow horse calling only near stable 
Config.calldistance = 50 -- how far from stable coords does calling the horse stop 


--------------------------------------------------------------
Config.dontallowwagonintown = true 
Config.dontallowhorseintown = false 
Config.BannedTowns = {'Annesburg', 'Armadillo', 'Blackwater', 'Rhodes', 'Siska', 'StDenis', 'Strawberry', 'Tumbleweed', 'Valentine', 'Vanhorn'}
--------------------------------------------------------------
Config.gumfarming = true -- toggle to true if using gum farming
Config.syn_outfitter = true
Config.joblock = false -- turn to true if you want to lock the buy functions to people with a job only 
Config.EnableBuyJobs = {'horsetrainer','trainer','bvs','bluebirdstables','sdstable','aceseightsstable','sewerratstable','caligastable','queenheartstable','vanhornstable','newaustinstable','rathskellerstable','armadillostable'} -- jobs that can buy
Config.horsedistancecall = 200 -- distance where if the horse is further it will despawn and a new horse will go to player 

Config.supporterselection = true -- supporter only horses, use only if vorp
Config.joblock2 = true -- job lock specific horses can be used for both vorp and redem 

-- only use ints, whole numbers no 1.5 or 0.5 
Config.trainermult = 2 -- any exp generated by a trainer is doubled to decrease reduce the multiplyer to 1
Config.othermult = 1 -- multiply the training points by 1 for non trainers


Config.commands = { -- only change the hashes
["horserest"] = "horserest", --U
["horsewallow"] = "horsewallow", --J
["horsesleep"] = "horsesleep", --H
["horsedrink"] = "horsedrink", --ALT Rear up
}

Config.horsesellrate = 0.3
Config.wagonsellrate = 0.5

Config.keys = { -- only change the hashes
["one"] = 0xD8F73058, --U
["two"] = 0xF3830D8E, --J
["three"] = 0x24978A28, --H
["four"] = 0x8AAA0AD4, --ALT Rear up
["five"] = 0xD9D0E1C0, --space Rear up
["six"] = 0xCEFD9220, -- E -- 

}
Config.horsehealcost = 5 -- cost to heal horse after its dead 
Config.deadtimer = 150000 -- time until horse can be called again, set to 2.5 minutes 
Config.traineronly = true -- only trainers can increase exp
Config.horselead = 30000 -- every 20 seconds increase by 1 bonding for leading
Config.horseride = 50000 -- every 40 seconds increase by 1 bonding for riding
Config.spawnrange = 50.0 ---- make sure the number has .0 in the end, for example 10.0 or 5.0(spawn horse in direction player is facing this amount of units away)
Config.spawnrangewagon = 50.0 ---- make sure the number has .0 in the end, for example 10.0 or 5.0(spawn horse in direction player is facing this amount of units away)
Config.stablelimit = 25 -- normal player stable limit 
Config.stablelimittrainer = 50 -- player with the horse trainer job limit
Config.horsetrainer = {"horsetrainer", "horsetamer","bvs","bluebirdstables","sdstable","macfarlanes","aceseightsstable","sewerratstable","caligastable","queenheartstable","vanhornstable","newaustinstable","rathskellerstable","armadillostable"} -- name of horse trainer job given to people in db
Config.wagonlimit = 40 -- limit for wagon stable slots
Config.Stables = { -- very tricky to add more. spawnpoint 1 is for horses 2 is for wagons
	Valentine = {	   
		Pos = {x=-367.73, y=787.72, z=116.26},
		showBlip = true,
		Name = 'Stable',
        Heading = -30.65,
		SpawnPoint = {
			Pos = {x=-387.40, y=780.68, z=115.63},
			CamPos = {x=1, y=-3, z=0},
			Heading = 182.3
		},
		SpawnPoint2 = {
			Pos = {x=-387.40, y=780.68, z=115.63},
			CamPos = {x=1, y=-3, z=0},
			Heading = 336.88
        }
	},
	BlackWater = {
		Pos = {x=-873.167, y=-1366.040, z=43.531},
		showBlip = true,
        Name = 'Stable',
        Heading = 266.84,
        SpawnPoint = {
            Pos = {x=-881.32, y=-1382.7, z=43.8},
            CamPos = {x=-4, y=-5, z=3},
            Heading = 181.91
        },
        SpawnPoint2 = {
            Pos = {x=-881.32, y=-1382.7, z=43.0},
            CamPos = {x=-5, y=-5, z=3},
            Heading = 336.88
        }
    },
    Saint_Denis = {
		Pos = {x=2503.153, y=-1442.725, z=46.312},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=2501.09, y=-1430.4, z=46.0},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 7.2
        },
        SpawnPoint2 = {
            Pos = {x=2501.09, y=-1430.4, z=45.6},
            CamPos = {x=-10, y=10, z=0},
            Heading = 7.2
        }
    },

	bvs = {
		Pos = {x=-2554.15, y=399.35, z=148.15},
		showBlip = true,
        Name = 'Big Valley Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-2544.479, y=419.109, z=148.318},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 357.005
        },
        SpawnPoint2 = {
            Pos = {x=-2540.230, y=418.377, z=148.215},
            CamPos = {x=-5, y=5, z=0},
            Heading = 357.005
        }
    },

	Rhodes = {
		Pos = {x=1432.61, y=-1294.74, z=77.82},
		showBlip = true,
        Name = 'Rhodes Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=1424.25, y=-1311.74, z=77.60},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 94.64
        },
        SpawnPoint2 = {
            Pos = {x=1419.60, y=-1312.26, z=77.62},
            CamPos = {x=-5, y=5, z=0},
            Heading = 285.805
        }
    },

	Caliga = {
		Pos = {x=1861.60, y=-1368.07, z=42.25},
		showBlip = true,
        Name = 'Caliga Stable',
        Heading = 206.13,
        SpawnPoint = {
            Pos = {x=1870.07, y=-1385.40, z=42.45},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 94.64
        },
        SpawnPoint2 = {
            Pos = {x=1870.71, y=-1388.38, z=42.36},
            CamPos = {x=-5, y=5, z=0},
            Heading = 285.805
        }
    },

	macfarlanes = {
		Pos = {x=-2418.36, y=-2392.81, z=61.17},
		showBlip = true,
        Name = 'Macfarlanes Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-2426.88, y=-2371.21, z=61.17},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 94.64
        },
        SpawnPoint2 = {
            Pos = {x=-2430.51, y=-2367.38, z=61.17},
            CamPos = {x=-5, y=5, z=0},
            Heading = 285.805
        }
    },

	tumbleweed = {
		Pos = {x=-5521.27, y=-3044.57, z=-2.38},
		showBlip = true,
        Name = 'Tumbleweed Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-5500.55, y=-3032.37, z=-3.95},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 269.16
        },
        SpawnPoint2 = {
            Pos = {x=-5500.55, y=-3032.37, z=-3.95},
            CamPos = {x=-5, y=5, z=0},
            Heading = 102.71
        }
    },

	rathskellerstable = {
		Pos = {x=-5204.63, y=-2149.50, z=12.12},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-5217.36, y=-2132.40, z=12.09},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 269.16
        },
        SpawnPoint2 = {
            Pos = {x=-5217.36, y=-2132.40, z=12.09},
            CamPos = {x=-5, y=5, z=0},
            Heading = 102.71
        }
    },

	armadillo = {
		Pos = {x=-3701.50, y=-2571.08, z=-13.71},
		showBlip = true,
        Name = 'Stables',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-3699.71, y=-2535.05, z=-13.97},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 323.16
        },
        SpawnPoint2 = {
            Pos = {x=-3700.82, y=-2527.46, z=-13.96},
            CamPos = {x=-5, y=5, z=0},
            Heading = 180.01
        }
    },
	bluesprivate = {
		Pos = {x=965.5, y=-1831.21, z=46.52},
		showBlip = false,
        Name = 'Bastille Stables',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=981.38, y=-1839.8, z=47.07},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 323.16
        },
        SpawnPoint2 = {
            Pos = {x=981.38, y=-1839.8, z=47.07},
            CamPos = {x=-5, y=5, z=0},
            Heading = 180.01
        }
    },
	strawberry = {
		Pos = {x=-1813.69, y=-563.77, z=156.08},
		showBlip = true,
        Name = 'Queen of Hearts Stables',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-1795.38, y=-566.26, z=156.08},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 323.16
        },
        SpawnPoint2 = {
            Pos = {x=-1795.38, y=-566.26, z=156.08},
            CamPos = {x=-5, y=5, z=0},
            Heading = 180.01
        }
    },
	vanhorn = {
		Pos = {x=2970.55, y=796.35, z=51.40},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=2973.69, y=781.05, z=51.23},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 323.16
        },
        SpawnPoint2 = {
            Pos = {x=2970.57, y=780.05, z=51.39},
            CamPos = {x=-5, y=5, z=0},
            Heading = 180.01
        }
    },
	emerald = {	   
		Pos = {x= 1384.24, y=352.22, z=87.58},
		showBlip = true,
		Name = 'Stable',
        Heading = -30.65,
		SpawnPoint = {
			Pos = {x=1391.22, y=336.48, z=87.60},
			CamPos = {x=1, y=-3, z=0},
			Heading = 182.3
		},
		SpawnPoint2 = {
			Pos = {x=1389.41, y=335.78, z=87.57},
			CamPos = {x=1, y=-3, z=0},
			Heading = 336.88
        }
	},

	wapiti = {	   
		Pos = {x= 478.64, y=2220.88, z=247.04},
		showBlip = true,
		Name = 'Stable',
        Heading = -30.65,
		SpawnPoint = {
			Pos = {x=487.20, y=2216.19, z=247.22},
			CamPos = {x=1, y=-3, z=0},
			Heading = 182.3
		},
		SpawnPoint2 = {
			Pos = {x=486.82, y=2221.61, z=247.11},
			CamPos = {x=1, y=-3, z=0},
			Heading = 336.88
        }
	},

	coulter = {	   
		Pos = {x= -1335.81, y=2398.15, z=307.10},
		showBlip = true,
		Name = 'Stable',
        Heading = -30.65,
		SpawnPoint = {
			Pos = {x=-1314.85, y=2403.85, z=306.86},
			CamPos = {x=1, y=-3, z=0},
			Heading = 182.3
		},
		SpawnPoint2 = {
			Pos = {x=-1314.52, y=2403.55, z=306.90},
			CamPos = {x=1, y=-3, z=0},
			Heading = 336.88
        }
	},
}

	
Config.wagons = { 
	{
		name = "Hunting",
		["huntercart01"] = {"Hunting Wagon", 0, 3000, 200,0,{"nojob"}},           
	},                                                                        ---------------NEW FEATURE -------------------
	{
		name = "Buggy",                                        ----name WAGON, gold , cash, inventory max items, supporter, job. 
		["buggy01"] = {"Buggy 1", 0, 600, 120,0,{"nojob"}},  ---- if gold 0 it wont show the gold option to pay
		["buggy02"] = {"Buggy 2", 0, 600, 120,0,{"nojob"}},   ---- if cash 0 it wont show an option to pay. 
		["buggy03"] = {"Buggy 3", 0, 600, 120,0,{"nojob"}},   -- you can enable  both or one by one.

	},
	{
		name= "Carts",
		["cart01"] = {"Cart 1", 0, 1000, 150,0,{"nojob"}},
		["cart02"] = {"Cart 2", 0, 1000, 150,0,{"nojob"}},
		["cart03"] = {"Cart 3", 0, 1000, 150,0,{"nojob"}},
		["cart04"] = {"Cart 4", 0, 1000, 150,0,{"nojob"}},
		["cart05"] = {"Cart 5", 0, 1000, 150,0,{"nojob"}},
		["cart06"] = {"Cart 6", 0, 1000, 150,0,{"nojob"}},
		["cart07"] = {"Cart 7", 0, 1000, 150,0,{"nojob"}},
		["cart08"] = {"Cart 8", 0, 1000, 120,0,{"nojob"}},
		["wagon05x"] = {"cart", 0, 1000, 150,0,{"nojob"}}, 

	},
	{
		name = "Other",
		["chuckwagon000x"] = {"Chuck Wagon 1", 0, 1500, 180,0,{"nojob"}},
		["chuckwagon002x"] = {"Chuck Wagon 2", 0, 1500, 180,0,{"nojob"}},
		["gatchuck"] = {"Gat Chuck 3", 0, 2000, 200,0,{"nojob"}},
		["utilliwag"] = {"Utillity Wagon", 0, 1500, 150,0,{"nojob"}},
		["wagon02x"] = {"Wagon", 0, 2000, 180,0,{"nojob"}},
		["wagon03x"] = {"Wagon 2", 0, 2000, 180,0,{"nojob"}},
		["wagon04x"] = {"Wagon 3", 0, 2000, 180,0,{"nojob"}},
		["wagon06x"] = {"Wagon 4", 0, 2000, 180,0,{"nojob"}},
	},
	{
		name = "Coachs",
		["coach2"] = {"Coach", 0, 2000, 140,0,{"nojob"}},
		["coach3"] = {"Coach 2", 0, 2000, 140,0,{"nojob"}},
		["coach4"] = {"Coach 3", 0, 2000, 140,0,{"nojob"}},
		["coach5"] = {"Coach 5", 0, 2000, 140,0,{"nojob"}},
		["coach6"] = {"Coach 5", 0, 2000, 140,0,{"nojob"}},
	},
	{
		name = "Stage Coach",
		["stagecoach001x"] = {"Coach 6", 0, 2000, 140,0,{"nojob"}},
		["stagecoach002x"] = {"Coach 7", 0, 2000, 140,0,{"nojob"}},
		["stagecoach003x"] = {"Coach 8", 0, 2000, 140,0,{"nojob"}},
		["stagecoach004x"] = {"Coach 9", 0, 2000, 140,0,{"nojob"}},
		["stagecoach005x"] = {"Coach 10", 0, 2000, 140,0,{"nojob"}},
		["stagecoach006x"] = {"Coach 11", 0, 2000, 140,0,{"nojob"}},
	},
	{
		name = "Wagons",
		["coal_wagon"] = {"Coal Wagon", 0, 2000, 140,0,{"nojob"}},
		["logwagon"] = {"Log Wagon", 0, 2000, 140,0,{"nojob"}},
		["oilWagon01x"] = {"Oil Wagon", 0, 2000, 140,0,{"nojob"}},
		["oilWagon02x"] = {"Oil Wagon 2", 0, 2000, 140,0,{"nojob"}},
		["supplywagon"] = {"Supply Wagon", 0, 2000, 180,0,{"nojob"}},
		["supplywagon"] = {"Supply Wagon", 0, 2000, 180,0,{"nojob"}},
		["wagonCircus02x"] = {"Circus Wagon", 0, 2000, 180,0,{"nojob"}},
		["wagonCircus01x"] = {"Circus Wagon 2", 0, 2000, 180,0,{"nojob"}},
		["wagondairy01x"] = {"Dairy Wagon", 0, 2000, 180,0,{"nojob"}},
		["wagondoc01x"] = {"Doctor Wagon", 0, 2000, 180,0,{"doctor"}},
		["wagontraveller01x"] = {"Traveller Wagon", 0, 2000, 180,0,{"nojob"}},
		["wagonwork01x"] = {"Baker Wagon", 0, 2000, 180,0,{"nojob"}},
	},
	{
		name = "Police",
		["gatchuck_2"] = {"Police Gatling 1", 0, 2000, 200,0,{"police"}}, 
		["policeWagongatling01x"] = {"Police Gatling 2", 0, 2000, 200,0,{"police"}}, 
		["ArmySupplyWagon"] = {"Army Supply Wagon", 0, 10000, 300,0,{"police","police2","police3"}}, 
		["wagonarmoured01x"] = {"Armored Wagon", 0, 2000, 140,0,{"police"}},
		["wagonPrison01x"] = {"Prison Wagon", 0, 2000, 180,0,{"police"}},
	},
	
}

Config.Horses = { -- please set all the prices to match your server eco correctly
		-- 4th slot is supporter level. has to match db characters 0 is the default is available for everyone
		--5th slot is job lock has to match the player job to be displayed. if player switches jobs while server is live they need to relog for the selection to reset
		-- 5th slot can be {"nojob"} to keep it open for everyone to buy

	{
		name = "American Paint", -- 3rd slot is the new slot. its important that you add it ! its the inventory max for the horse 
		["A_C_Horse_AmericanPaint_Greyovero"] = {"Grey", 0, 400,130,0,{"nojob"}}, -- first slot is gold 2nd slot is cash. 
		["A_C_Horse_AmericanPaint_Overo"] = {"Overo", 0, 400, 130,0,{"nojob"}},
		["A_C_Horse_AmericanPaint_SplashedWhite"] = {"Splashwhite", 0, 400, 130,0,{"nojob"}},
		["A_C_Horse_AmericanPaint_Tobiano"] = {"Tobiano", 0, 400, 130,0,{"nojob"}},
	
	},
	{
		name = "Gypsy Cob",
		["a_c_horse_gypsycob_palominoblagdon"] = {"palominoBlagdon", 0, 2000, 130,0,{"nojob"}},
		["a_c_horse_gypsycob_piebald"] = {"Piebald", 0, 2000, 130,0,{"nojob"}},
		["a_c_horse_gypsycob_splashedbay"] = {"SplashedBay", 0, 2000, 130,0,{"nojob"}},
		["a_c_horse_gypsycob_splashedpiebald"] = {"SplashedPiebald", 0, 2000, 130,0,{"nojob"}},
		["a_c_horse_gypsycob_skewbald"] = {"Skewbald", 0, 2000, 130,0,{"nojob"}},
		["a_c_horse_gypsycob_whiteblagdon"] = {"WhiteBlagdon", 0, 2000, 130,0,{"nojob"}},
	
	},
	{
		name = "American Standardbred",
		["A_C_Horse_AmericanStandardbred_Black"] = {"Black", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_AmericanStandardbred_Buckskin"] = {"Buckskin", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_AmericanStandardbred_PalominoDapple"] = {"PalominoDapple", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_AmericanStandardbred_SilverTailBuckskin"] = {"SilverTailBuckskin", 0, 200, 130,0,{"nojob"}},
	},
	{
		name = "Andalusian",
		["A_C_Horse_Andalusian_DarkBay"] = {"DarkBay", 0, 530, 130,0,{"nojob"}},
		["A_C_Horse_Andalusian_Perlino"] = {"Perlino", 0, 530, 130,0,{"nojob"}},
		["A_C_Horse_Andalusian_RoseGray"] = {"RoseGray", 0, 560, 130,0,{"nojob"}},    
	},
	{
		name = "Appaloosa",
		["A_C_Horse_Appaloosa_BlackSnowflake"] = {"BlackSnowflake", 0, 300, 130,0,{"nojob"}},
		["A_C_Horse_Appaloosa_Blanket"] = {"Blanket", 0, 300, 130,0,{"nojob"}},
		["A_C_Horse_Appaloosa_BrownLeopard"] = {"BrownLeopard", 0, 310, 130,0,{"nojob"}},
		["A_C_Horse_Appaloosa_FewSpotted_PC"] = {"FewSpots", 0, 320, 130,0,{"nojob"}},
		["A_C_Horse_Appaloosa_Leopard"] = {"Leopard", 0, 320, 130,0,{"nojob"}},
		["A_C_Horse_Appaloosa_LeopardBlanket"] = {"LeopardBlanket", 0, 320, 130,0,{"nojob"}},
	},
	{
		name = "Arabian",
		["A_C_Horse_Arabian_Black"] = {"BlackHorse", 0, 3000, 130,0,{"nojob"}},
		["A_C_Horse_Arabian_Grey"] = {"GreyHorse", 0, 3000, 130,0,{"nojob"}},
		["A_C_Horse_Arabian_RedChestnut"] = {"RedChestnut", 0, 3000, 130,0,{"nojob"}},
		["A_C_Horse_Arabian_RoseGreyBay"] = {"RoseGreyBay", 0, 3000, 130,0,{"nojob"}},
		["A_C_Horse_Arabian_WarpedBrindle_PC"] = {"WarpedBrindle", 0, 3000, 130,0,{"nojob"}},
		["A_C_Horse_Arabian_White"] = {"White", 0, 3000, 130,0,{"nojob"}},
	
	},
	{
		name = "Ardennes",
		["A_C_Horse_Ardennes_BayRoan"] = {"BayRoan", 0, 570, 130,0,{"nojob"}},
		["A_C_Horse_Ardennes_IronGreyRoan"] = {"IronGreyRoan", 0, 570, 130,0,{"nojob"}},
		["A_C_Horse_Ardennes_StrawberryRoan"] = {"StrawberryRoan", 0, 580, 130,0,{"nojob"}},
	},
	{
		name = "Belgian",
		["A_C_Horse_Belgian_BlondChestnut"] = {"BlondChestnut", 0, 230, 130,0,{"nojob"}},
		["A_C_Horse_Belgian_MealyChestnut"] = {"MealyChestnut", 0, 230, 130,0,{"nojob"}},
	},
	{
		name = "Dutch Warmblood",
		["A_C_Horse_DutchWarmblood_ChocolateRoan"] = {"ChocolateRoan", 0, 500, 130,0,{"nojob"}},
		["A_C_Horse_DutchWarmblood_SealBrown"] = {"SealBrown", 0, 500, 130,0,{"nojob"}},
		["A_C_Horse_DutchWarmblood_SootyBuckskin"] = {"SootyBuckskin", 0, 500, 130,0,{"nojob"}},
	},
	{
		name = "Hungarian Halfbred",
		["A_C_Horse_HungarianHalfbred_DarkDappleGrey"] = {"DarkDappleGrey", 0, 440, 130,0,{"nojob"}},
		["A_C_Horse_HungarianHalfbred_FlaxenChestnut"] = {"FlaxenChestnut", 0, 440, 130,0,{"nojob"}},
		["A_C_Horse_HungarianHalfbred_LiverChestnut"] = {"LiverChestnut", 0, 440, 130,0,{"nojob"}},
		["A_C_Horse_HungarianHalfbred_PiebaldTobiano"] = {"PiebaldTobiano", 0, 440, 130,0,{"nojob"}},
	},
	{
		name = "Kentucky Saddle",
		["A_C_Horse_KentuckySaddle_Black"] = {"BlackSaddler", 0, 170, 130,0,{"nojob"}},
		["A_C_Horse_KentuckySaddle_ButterMilkBuckskin_PC"] = {"ButterMilkBuckskin", 0, 170, 130,0,{"nojob"}},
		["A_C_Horse_KentuckySaddle_ChestnutPinto"] = {"ChestnutPinto", 0, 170, 130,0,{"nojob"}},
		["A_C_Horse_KentuckySaddle_Grey"] = {"GreySaddler", 0, 170, 130,0,{"nojob"}},
		["A_C_Horse_KentuckySaddle_SilverBay"] = {"SilverBay", 0, 170, 130,0,{"nojob"}},
	},
	{
		name = "Kladruber",
		["A_C_Horse_Kladruber_Black"] = {"BlackKladruber", 45, 1300, 130,0,{"nojob"}},
		["A_C_Horse_Kladruber_Silver"] = {"Silver", 45, 1300, 130,0,{"nojob"}},
		["A_C_Horse_Kladruber_Cremello"] = {"Cremello", 45, 1300, 130,0,{"nojob"}},
		["A_C_Horse_Kladruber_Grey"] = {"GreyKladruber", 45, 1300, 130,0,{"nojob"}},
		["A_C_Horse_Kladruber_DappleRoseGrey"] = {"DappleRoseGrey", 45, 1300, 130,0,{"nojob"}},
		["A_C_Horse_Kladruber_White"] = {"WhiteKladruber", 45, 1300, 130,0,{"nojob"}},
	},
	{
		name = "Missouri Fox Trotter",
		["A_C_Horse_MissouriFoxTrotter_AmberChampagne"] = {"AmberChampagne", 0, 1800, 130,0,{"nojob"}},
		["A_C_Horse_MissouriFoxTrotter_SableChampagne"] = {"SableChampagne", 0, 1800, 130,0,{"nojob"}},
		["A_C_Horse_MissouriFoxTrotter_SilverDapplePinto"] = {"SilverDapplePinto", 0, 1800, 130,0,{"nojob"}},
        ["a_c_horse_missourifoxtrotter_blacktovero"] = {"blackTrovero", 0, 1800, 130,0,{"nojob"}},   
        ["a_c_horse_missourifoxtrotter_blueroan"] = {"blue", 0, 1800, 130,0,{"nojob"}},   
        ["a_c_horse_missourifoxtrotter_buckskinbrindle"] = {"buckskinBrindle", 0, 1800, 130,0,{"nojob"}},  
        ["a_c_horse_missourifoxtrotter_dapplegrey"] = {"dapplegrey", 0, 1800, 130,0,{"nojob"}},
	},
	{
		name = "Morgan",
		["A_C_Horse_Morgan_Bay"] = {"Bay", 0, 40, 130,0,{"nojob"}},
		["A_C_Horse_Morgan_BayRoan"] = {"BayRoanH", 0, 40, 130,0,{"nojob"}},
		["A_C_Horse_Morgan_FlaxenChestnut"] = {"Flaxen", 0, 40, 130,0,{"nojob"}},
		["A_C_Horse_Morgan_LiverChestnut_PC"] = {"Liver", 0, 40, 130,0,{"nojob"}},
		["A_C_Horse_Morgan_Palomino"] = {"Palomino", 0, 40, 130,0,{"nojob"}},
	},
	{
		name = "Mustang",
		["A_C_Horse_Mustang_GoldenDun"] = {"GoldenDun", 0, 380, 130,0,{"nojob"}},
		["A_C_Horse_Mustang_GrulloDun"] = {"GrulloDun", 0, 380, 130,0,{"nojob"}},
		["A_C_Horse_Mustang_TigerStripedBay"] = {"TigerStripedBay", 0, 380, 130,0,{"nojob"}},
		["A_C_Horse_Mustang_WildBay"] = {"WildBay", 0, 380, 130,0,{"nojob"}},
		["a_c_horse_mustang_blackovero"] = {"black overo", 0, 380, 130,0,{"nojob"}},    
        ["a_c_horse_mustang_buckskin"] = {"BuckSkinn", 0, 380, 130,0,{"nojob"}},  
        ["a_c_horse_mustang_chestnuttovero"] = {"ChestnutTovero", 0, 380, 130,0,{"nojob"}}, 
        ["a_c_horse_mustang_reddunovero"] = {"RedDunOvero", 0, 380, 130,0,{"nojob"}},   
	},
	{
		name = "Nokota",
		["A_C_Horse_Nokota_BlueRoan"] = {"BlueRoan", 0, 340, 130,0,{"nojob"}},
		["A_C_Horse_Nokota_ReverseDappleRoan"] = {"ReverseDappleRoan", 0, 360, 130,0,{"nojob"}},
		["A_C_Horse_Nokota_WhiteRoan"] = {"WhiteRoan", 0, 340, 130,0,{"nojob"}},
	},
	{
		name = "Shire",
		["A_C_Horse_Shire_DarkBay"] = {"Dark", 0, 250, 130,0,{"nojob"}},
		["A_C_Horse_Shire_LightGrey"] = {"LightGrey", 0, 250, 130,0,{"nojob"}},
		["A_C_Horse_Shire_RavenBlack"] = {"RavenBlack", 0, 270, 130,0,{"nojob"}},
	},
	{
		name = "Suffolk Punch",
		["A_C_Horse_SuffolkPunch_RedChestnut"] = {"Red", 0, 270, 130,0,{"nojob"}},
		["A_C_Horse_SuffolkPunch_Sorrel"] = {"Sorrel", 0, 270, 130,0,{"nojob"}},
	},
	{
		name = "Tennessee Walker",
		["A_C_Horse_TennesseeWalker_BlackRabicano"] = {"BlackRabicano", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_Chestnut"] = {"Chestnut", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_DappleBay"] = {"DappleBay", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_FlaxenRoan"] = {"FlaxenRoan", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_MahoganyBay"] = {"MahoganyBay", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_RedRoan"] = {"RedRoan", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_GoldPalomino_PC"] = {"GoldPalomino", 0, 200, 130,0,{"nojob"}},
	},
	{
		name = "Thoroughbred",
		["A_C_Horse_Thoroughbred_BlackChestnut"] = {"BlackChestnut", 0, 380, 130,0,{"nojob"}},
		["A_C_Horse_Thoroughbred_BloodBay"] = {"BloodBay", 0, 200, 130,0,{"nojob"}},
		["A_C_Horse_Thoroughbred_Brindle"] = {"Brindle", 0, 380, 130,0,{"nojob"}},
		["A_C_Horse_Thoroughbred_DappleGrey"] = {"Dapple", 0, 250, 130,0,{"nojob"}},
		["A_C_Horse_Thoroughbred_ReverseDappleBlack"] = {"DappleBlack", 0, 400, 130,0,{"nojob"}},
	},
	{
		name = "Turkoman",
		["A_C_Horse_Turkoman_DarkBay"] = {"Darkturko", 0, 1700, 130,0,{"nojob"}},
		["A_C_Horse_Turkoman_Gold"] = {"Gold turko", 0, 1700, 130,0,{"nojob"}},
		["A_C_Horse_Turkoman_Silver"] = {"Silver turko", 0, 1700, 130,0,{"nojob"}},
		["a_c_horse_turkoman_black"] = {"black Turko", 0, 1700, 130,0,{"nojob"}},   
        ["a_c_horse_turkoman_chestnut"] = {"chestnut turko", 0, 1700, 130,0,{"nojob"}},
		["a_c_horse_turkoman_grey"] = {"grey turko", 0, 1700, 130,0,{"nojob"}},    
        ["a_c_horse_turkoman_perlino"] = {"perlino turko", 0, 1700, 130,0,{"nojob"}},
	},
	{
		name = "Criollo",
		["A_C_Horse_Criollo_Dun"] = {"Dun", 0, 500, 130,0,{"nojob"}},
		["A_C_Horse_Criollo_MarbleSabino"] = {"MarbleSabino", 0, 500, 130,0,{"nojob"}},
		["A_C_Horse_Criollo_BayFrameOvero"] = {"BayFrameOvero", 0, 500, 130,0,{"nojob"}},
		["A_C_Horse_Criollo_BayBrindle"] = {"BayBrindle", 0, 500, 130,0,{"nojob"}},
		["A_C_Horse_Criollo_SorrelOvero"] = {"SorrelOvero", 0, 500, 130,0,{"nojob"}},
		["A_C_Horse_Criollo_BlueRoanOvero"] = {"BlueRoanOvero", 0, 500, 130,0,{"nojob"}},
	},
	{
		name = "Breton",
		["A_C_Horse_Breton_SteelGrey"] = {"SteelGrey", 0, 560, 130,0,{"nojob"}},
		["a_c_horse_breton_mealydapplebay"] = {"MealyDapple", 0, 560, 130,0,{"nojob"}},
		["A_C_Horse_Breton_SealBrown"] = {"Seal", 0, 560, 130,0,{"nojob"}},
		["A_C_Horse_Breton_GrulloDun"] = {"GrulloDun", 0, 560, 130,0,{"nojob"}},
		["A_C_Horse_Breton_Sorrel"] = {"SorrelBreton", 0, 560, 130,0,{"nojob"}},
		["A_C_Horse_Breton_RedRoan"] = {"Roan Red", 0, 560, 130,0,{"nojob"}},
	},
	{
		name = "Norfolk Roadster",
		["A_C_HORSE_NORFOLKROADSTER_BLACK"] = {"BlackNor", 0, 600, 130,0,{"nojob"}},
		["A_C_HORSE_NORFOLKROADSTER_SPECKLEDGREY"] = {"SpeckLedGrey", 0, 600, 130,0,{"nojob"}},
		["A_C_HORSE_NORFOLKROADSTER_PIEBALDROAN"] = {"PiebaldRoan", 0, 600, 130,0,{"nojob"}},
		["A_C_HORSE_NORFOLKROADSTER_ROSEGREY"] = {"Grey Rose", 0, 600, 130,0,{"nojob"}},
		["A_C_HORSE_NORFOLKROADSTER_DAPPLEDBUCKSKIN"] = {"DappleBuck", 0, 600, 130,0,{"nojob"}},
		["A_C_HORSE_NORFOLKROADSTER_SPOTTEDTRICOLOR"] = {"SpottedTri", 0, 600, 130,0,{"nojob"}},
	},
	{
		name = "Old Penco",
		["A_C_Horse_MP_Mangy_Backup"] = {"Mangy", 15, 15, 130,0,{"nojob"}},
		["A_C_HorseMulePainted_01"] = {"Zebra", 0, 5000, 130,0,{"nojob"}},
		["A_C_HorseMule_01"] = {"Mule", 0, 20, 130,0,{"nojob"}},
		["A_C_Donkey_01"] = {"Donkey", 0, 20, 130,0,{"nojob"}},
	},
	{
		name = "Rare",
		["p_c_horse_01"] = {"Horse", 1, 1, 30,5,{"nojob"}},
		["a_c_horse_americanstandardbred_lightbuckskin"] = {"Standardbred Light buckskin", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_arabian_redchestnut_pc"] = {"Special Red Arabian", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_arabian_redchestnut_pc"] = {"Special Red Arabian", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_buell_warvets"] = {"Buell Warvets", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_eagleflies"] = {"Eagleflies", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_bill"] = {"Bills", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_charles"] = {"Charles", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_charles_endlesssummer"] = {"Charles 2", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_dutch"] = {"Dutch", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_hosea"] = {"Hosea", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_javier"] = {"Javier", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_john"] = {"John", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_karen"] = {"Karen", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_kieran"] = {"Kieran", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_lenny"] = {"Lenny", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_micah"] = {"Micha", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_sadie"] = {"Sadie", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_sadie_endlesssummer"] = {"Sadie 2", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_sean"] = {"Sean", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_trelawney"] = {"Trelawney", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_uncle"] = {"Uncle", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_gang_uncle_endlesssummer"] = {"Uncle 2", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_john_endlesssummer"] = {"John 2", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_murfreebrood_mange_01"] = {"Murfreebrood Mange 1", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_murfreebrood_mange_02"] = {"Murfreebrood Mange 2", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_murfreebrood_mange_03"] = {"Murfreebrood Mange 3", 1, 1, 130,5,{"nojob"}},
		["a_c_horse_winter02_01"] = {"Winter", 1, 1, 130,5,{"nojob"}},

	},
}

Config.Language = { -- space is very important edit your language here ! 
	["qt"] = "Invalid quantity",
	["nojobreq"] = "You Dont Have The Correct Job To Use This Wagon",
	["horsemax"] = "your horse cant carry more items, saddle limit is ",	
	["wagonmax"] = "your wagon cant store more items, inventory limit limit is ",	
	["carry"] = "You cant carry more items",
    ["limit"] = "You reached the limit for this item",
    ["givehorse"] = "You gave your horse to ",
    ["givewagon"] = "You gave your wagon to ",
    ["receiveHorse"] = "You received a horse ownership deed from ",
    ["receivewagon"] = "You received a wagon ownership deed from ",
    ["horselimit"] = " tried to give you a horse but you are at your stables slot limit",
    ["wagonlimit"] = " tried to give you a wagon but you are at your stables wagon limit",
    ["horselimit2"] = " is at stable slot limit",
    ["wagonlimit2"] = " is at stable slot limit",
	["wrongid"] = "Wrong ID",
	["nogold"] = "Not Enough Gold",
	["nocash"] = "Not Enough Cash",
	["limitwagon"] = "You cant buy more wagons.",
	["limithorse"] = "You cant buy more horses.",
	["horsesold"] = "You have sold your horse",
	["wagonsold"] = "You have sold your wagon",
	["open"] = "Open Stable",
	["stable"] = "Stable",
	["name"] = "Name your horse:",
	["name2"] = "Name your wagon:",
	["nowagon"] = "you dont have a wagon selected",
	["nohorse"] = "you dont have a horse selected",
	["horseinfo"] = "Horse Info:",
	["wagoninfo"] = "Wagon Info:",
	["sure"] = "Are You Sure?",
	["horsename"] = "Horse Name: ",
	["horsetrainlevel"] = "Horse Training Level: ",
	["horsetrainexp"] = "Horse Training Exp: ",
	["givehorseowner"] = "Give Horse Ownership",
	["saddlebags"] = "Saddle Bags",
	["wagonname"] = "Wagon Name: ",
	["dismiss"] = "Dismiss Wagon",
	["givewagonowner"] = "Give Wagon Ownership",
	["wagoninv"] = "Inventory",
	["yes"] = "YES",
	["no"] = "NO",
	["wagon"] = "Wagon",
	["tired"] = "you are too tired to train your horse",
	["tired2"] = "you need some rest. horse training stopped wait 5 minutes",
	["better"] = "you feel better and can train your horse",
	["level2"] = "you need horse training level 2",
	["level3"] = "you need horse training level 3",
	["level4"] = "you need horse training level 4",
	["water"] = "your horse is not in water",
	["deadhorse"] = "your horse is injured please try again shortly", 
	["payfordead"] = "your horse was healed by the vet, you paid ",
	["equipment"] = "Outfitter Menu",
	["sex"] = "Horse Sex",
	["cancel"] = "Cancel Buying",
	["male"] = "Male",
	["female"] = "Female",
	["toofarfromstable"] = "Too Far From Stable",
	["someonesearch"] = "Someone is Searching already", 
	["tooclosetown"] = "too close to town",
	["waypoint"] = "Waypoint", 
	["processing"] = "Please Wait",
	["attemptybuy"] = "Attempted Buy",
	["attemptybuy2"] = "Attempted buying via exploit. by logging out after naming",
	["boughthorse"] = "buy",
	["seoldhorse"] = "sold",
	["withdrawhorse"] = "withdraw item from horse",
	["depohorse"] = "deposit item to horse",
	["depowagon"] = "deposit item to wagon",
	["withdrawwagon"] = "withdraw item from wagon",
	["information"] = "info: ",
	["discord1"] = "Discord of user:",
	["discord2"] = "username of user:",
	["discord3"] = "Discord of owner:",
	["purchasedcomps"] = "You Purchased Tack for $", -- new line
	["blacklisteditem"] = "Item is blacklisted can not be storedin here",
}
